<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.tacticnav</groupId>
        <artifactId>tactic-nav-parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>radar-simulator</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.tacticnav.radar.Main</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>copy-jars-to-bin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <mkdir dir="../bin"/>

                                <copy file="${project.build.directory}/${project.artifactId}-${project.version}-jar-with-dependencies.jar"
                                      tofile="../bin/${project.artifactId}-${project.version}-jar-with-dependencies.jar"
                                      failonerror="false"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

    <profiles>
        <profile>
            <id>spotbugs</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>spotbugs-check</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>spoon-check</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>fr.inria.gforge.spoon</groupId>
                        <artifactId>spoon-maven-plugin</artifactId>
                        <version>3.8.0</version>
                        <executions>
                            <execution>
                                <id>spoon-comment-check</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <compliance>${maven.compiler.release}</compliance>
                            <enableComments>true</enableComments>
                            <noClasspath>true</noClasspath>
                            <skipGeneratedSources>true</skipGeneratedSources>
                            <processors>
                                <processor>com.tacticnav.spoon.NoCommentInsideMethodProcessor</processor>
                            </processors>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>com.tacticnav</groupId>
                                <artifactId>radar-spoon-rules</artifactId>
                                <version>${project.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>fr.inria.gforge.spoon</groupId>
                                <artifactId>spoon-core</artifactId>
                                <version>10.4.1</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>static-analysis</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>spotbugs-check</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>fr.inria.gforge.spoon</groupId>
                        <artifactId>spoon-maven-plugin</artifactId>
                        <version>3.8.0</version>
                        <executions>
                            <execution>
                                <id>spoon-comment-check</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <compliance>${maven.compiler.release}</compliance>
                            <enableComments>true</enableComments>
                            <noClasspath>true</noClasspath>
                            <skipGeneratedSources>true</skipGeneratedSources>
                            <processors>
                                <processor>com.tacticnav.spoon.NoCommentInsideMethodProcessor</processor>
                            </processors>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>com.tacticnav</groupId>
                                <artifactId>radar-spoon-rules</artifactId>
                                <version>${project.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>fr.inria.gforge.spoon</groupId>
                                <artifactId>spoon-core</artifactId>
                                <version>10.4.1</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
